### ISSUE TITLE
Get error message while running 

### ISSUE THREAD

**Issue by yuyongmao** [AuthorizeNet/accept-sample-ios-objectivec#2]
Xcode 9.3

error message:
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/**********/Library/Developer/CoreSimulator/Devices/**********/data/Containers/Bundle/Application/**********/accept-sample-objc.app/Frameworks/AcceptSDK.framework/AcceptSDK
  Reason: image not found

**Comment by piotrilski** [comment]
Getting the same error

**Comment by RaviNguyen** [comment]
Have save error :(

**Comment by ghost** [comment]
Hi @yuyongmao, thanks for reaching out to us. We have updated the SDK. Please update the pod and try with latest version of SDK.
